### ISSUE TITLE
cannot access to any url that has been protected by jwt

### ISSUE THREAD

**Issue by GiantCaiB** [cornflourblue/node-jwt-authentication-api#1]
Hi Jason,

Thanks for posting this handle and helpful repository.

While I am using this solution in my own project( even directly on this original version), I found that I cannot access to the urls that are NOT listed in `expressJwt({ secret }).unless()`, no matter in the Postman with basic auth or the implemented front end. The only one working way is that I printed the generated token in the console and copy-pasted in the Postman via bearer token...

Is there anything I missed?  Appreciate for your answer!

Danny

**Comment by piks2252** [comment]
hi @GiantCaiB , how you solved this issue, i hace same problem when access any url that has been protected by jwt.
i am getting access denied error.
